# Generated by Django 6.0.6 on 2026-07-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('publisher_name', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(blank=True, max_length=24)),
                ('title_i18n', models.JSONField(default=dict)),
                ('summary_i18n', models.JSONField(blank=True, default=dict)),
                ('body_i18n', models.JSONField(blank=True, default=dict)),
                ('published_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='companies.company')),
            ],
            options={
                'ordering': ['-published_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.newsarticle')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
