# Generated by Django 6.0.6 on 2026-07-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RndSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('name_i18n', models.JSONField(default=dict)),
                ('description_i18n', models.JSONField(blank=True, default=dict)),
                ('patent_requested', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rnd_submissions', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
