from .base import *  # noqa: F403

DEBUG = False
APP_FORCE_HTTPS = env("APP_FORCE_HTTPS")  # noqa: F405
SECURE_SSL_REDIRECT = True if APP_FORCE_HTTPS else env("SECURE_SSL_REDIRECT")  # noqa: F405
SESSION_COOKIE_SECURE = True if APP_FORCE_HTTPS else env("SESSION_COOKIE_SECURE")  # noqa: F405
CSRF_COOKIE_SECURE = True if APP_FORCE_HTTPS else env("CSRF_COOKIE_SECURE")  # noqa: F405
JWT_COOKIE_SECURE = True if APP_FORCE_HTTPS else env("JWT_COOKIE_SECURE")  # noqa: F405
SECURE_HSTS_SECONDS = env("SECURE_HSTS_SECONDS")  # noqa: F405
SECURE_HSTS_INCLUDE_SUBDOMAINS = env("SECURE_HSTS_INCLUDE_SUBDOMAINS")  # noqa: F405
SECURE_HSTS_PRELOAD = env("SECURE_HSTS_PRELOAD")  # noqa: F405
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
