# Generated by Django 6.0.6 on 2026-07-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('from_name', models.CharField(blank=True, max_length=180)),
                ('contact', models.CharField(blank=True, max_length=180)),
                ('subject_i18n', models.JSONField(blank=True, default=dict)),
                ('message_i18n', models.JSONField(blank=True, default=dict)),
                ('raw_message', models.TextField(blank=True)),
                ('official', models.BooleanField(default=False)),
                ('reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('voice', 'Voice')], max_length=16)),
                ('file', models.FileField(upload_to='complaints/')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.complaint')),
            ],
        ),
    ]
